[project]
name = "aorus-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "huggingface-hub[cli]>=0.36.2",
    "llama-cpp-python>=0.3.35",
    "numpy>=2.0.2",
    "requests>=2.32.5",
    "sentence-transformers>=5.1.2",
]

[project.scripts]
aorus-rag = "aorus_rag:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
